@TaskTracker_HostAddress = http://localhost:5078

GET {{TaskTracker_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{TaskTracker_HostAddress}}/api/tasks/
Accept: application/json

###
POST {{TaskTracker_HostAddress}}}/api/tasks
Accept: application/json
Content-Type: application/json
{
"id": 0,
"message": "hello"
}